package ar.com.ericpennachini.fashiondog.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val md_theme_light_primary = Color(0xFF7345b7)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFeedcff)
val md_theme_light_onPrimaryContainer = Color(0xFF270057)
val md_theme_light_secondary = Color(0xFF006879)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFa1eeff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f25)
val md_theme_light_tertiary = Color(0xFF1e57c8)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFdae2ff)
val md_theme_light_onTertiaryContainer = Color(0xFF00174b)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfdfbff)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfdfbff)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f4)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inversePrimary = Color(0xFFd8baff)
val md_theme_light_shadow = Color(0xFF000000)

// Dark theme
val md_theme_dark_primary = Color(0xFFd8baff)
val md_theme_dark_onPrimary = Color(0xFF430586)
val md_theme_dark_primaryContainer = Color(0xFF5a299d)
val md_theme_dark_onPrimaryContainer = Color(0xFFeedcff)
val md_theme_dark_secondary = Color(0xFF53d7f1)
val md_theme_dark_onSecondary = Color(0xFF003640)
val md_theme_dark_secondaryContainer = Color(0xFF004e5b)
val md_theme_dark_onSecondaryContainer = Color(0xFFa1eeff)
val md_theme_dark_tertiary = Color(0xFFb1c5ff)
val md_theme_dark_onTertiary = Color(0xFF002a77)
val md_theme_dark_tertiaryContainer = Color(0xFF003fa6)
val md_theme_dark_onTertiaryContainer = Color(0xFFdae2ff)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe4e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)
val md_theme_dark_inversePrimary = Color(0xFF7345b7)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
